language: python

sudo: false

branches:
  except:
    - yellowstone-env

env:
  - CONDA_PYTHON="python=2.7"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update --all --yes
  - conda info -a

install:
  - conda env create -f environment.yml
  - source activate ugrid-tools
  - conda remove -y ocgis
  - ( cd /tmp && git clone -b pmesh-ugrid-nfie https://github.com/NCPP/ocgis.git && cd ocgis && python setup.py install )

script:
  # This runs the full suite of tests.
  - source activate ugrid-tools
  - bash test.sh
  - python setup.py install
  - python -c "import utools"
  - utools_cli --help

  # Test OCGIS and RTree are optional Python dependencies.
  - source activate ugrid-tools
  - conda remove -y ocgis rtree
  - bash test.sh
  - python setup.py install
  - python -c "import utools"
  - utools_cli --help

  # Test ESMF format conversion can occur without Fiona.
  - source activate ugrid-tools
  - conda remove -y fiona
  - cd src
  - nosetests utools.test.test_utools.test_prep.test_prep_shapefiles:Test.test_convert_to_esmf_format
